### ISSUE TITLE
Update email template layout to include MENA devs logo and theme colours

### ISSUE THREAD

**Issue by cnicolaou** [mena-devs/tilde#4]

**Comment by HassanKanj** [comment]
I will work on this, how can I assign myself to this task?

**Comment by Link-** [comment]
Hmm you should be able to do so in the right panel, under "Assignees".

**Comment by HassanKanj** [comment]
yeah I saw it, but there's no button for 'add', maybe a permission issue.. @costa can you assign this task to me

**Comment by cnicolaou** [comment]
Yes, go for it Hassan

**Comment by cnicolaou** [comment]
@HassanKanj i am also working on this.
