### ISSUE TITLE
Add invitation API to the swagger file

### ISSUE THREAD

**Issue by Link-** [mena-devs/tilde#57]
Heyy, we need the invitation API in swagger to auto generate the clients for all tilde's APIs.

```
endpoint: https://menadevs.com/api/v1/invitations
```

**Comment by constantine-nikolaou** [comment]
@Link- I am deploying the changes live.

**Comment by Link-** [comment]
@constantine-nikolaou ya3tik l 3afieh. Quick question, are these breaking changes? In the old version the API token is passed in the URL I think as a query string but in the spec it's a Bearer token. Are we backward compatible?

**Comment by constantine-nikolaou** [comment]
Of course, we are backward compatible indeed
