### ISSUE TITLE
Bug: Error when executing "bin/setup" (because of omniauth.rb)

### ISSUE THREAD

**Issue by HassanKanj** [mena-devs/tilde#8]
I was trying to execute bin/setup but I encountered an error, it turns out the exception was thrown from the file `omniauth.rb`, and I was able to fix it by adding some "dummy" values for: 

`slack_app_client_id` and `slack_app_client_secret`

so maybe we can fix this issue by adding some "dummy" values to these configs in **development.example.yml** ?

these are some screenshots:

![error](https://user-images.githubusercontent.com/6857592/28394892-dbda556e-6cf8-11e7-8673-8d30ecb9523b.jpg)

![omniauth](https://user-images.githubusercontent.com/6857592/28394901-e193bfc2-6cf8-11e7-9c02-5872fdb10420.png)

Solution:

![solution](https://user-images.githubusercontent.com/6857592/28394908-eb107de2-6cf8-11e7-9b26-327cc44087c6.jpg)

**Comment by cnicolaou** [comment]
Good find @HassanKanj, however you don't need to run `bin/setup` if you've downloaded and using the vagrant box.
I'll fix this one anyway not to throw an exception but to continue the setup process.
