### ISSUE TITLE
updating the documentation on how to use the vagrant box

### ISSUE THREAD

**Issue by HassanKanj** [mena-devs/tilde#9]
I was talking to @phr34ck and it seems there's a missing step (or two?) in the readme on how to use the vagrant box

The main missing step is:

`vagrant init BOX_NAME_HERE`

and I think it is a good idea to change the box name back from **ubuntu/xenial64** to **tilde**

@phr34ck can you confirm that?

**Comment by phr34ck** [comment]
you can name the box when using `vagrant box add` command to whatever you want and according to the current Vagrantfile, the box is expected to be named **ubuntu/xenial64**.

`vagrant init` is missing from the readme file and it should use the actual boxname found in the config file.

**Comment by cnicolaou** [comment]
Guys, the name (ubuntu/xenial64) is the name of the base box that Vagrant uses.
There is no need to run `vagrant init` as it will replace existing `Vagrantfile` inside the repository.

The steps needed to set you up are:
- Download the box
- from the repo, run `vagrant box add ubuntu/xenial64 ~/path-to-downloaded-box-after-decompressing`
- run `vagrant up`
- login to the box `vagrant ssh`

**Comment by cnicolaou** [comment]
This is also why we use a mirror to build our image on top of it: regular updates

```
md.com(master)$ vagrant box update
==> default: Checking for updates to 'ubuntu/xenial64'
    default: Latest installed version: 20170717.0.0
    default: Version constraints:
    default: Provider: virtualbox
==> default: Updating 'ubuntu/xenial64' with provider 'virtualbox' from version
==> default: '20170717.0.0' to '20170719.0.0'...
==> default: Loading metadata for box 'https://atlas.hashicorp.com/ubuntu/xenial64'
==> default: Adding box 'ubuntu/xenial64' (v20170719.0.0) for provider: virtualbox
    default: Downloading: https://app.vagrantup.com/ubuntu/boxes/xenial64/versions/20170719.0.0/providers/virtualbox.box
==> default: Successfully added box 'ubuntu/xenial64' (v20170719.0.0) for 'virtualbox'!
```

**Comment by HassanKanj** [comment]
The problem was that I didn't run the commands "from the project directory", now it makes sense (since Vagrantfile already exist in the repo).
Thanks @cnicolaou for the additional explanation.
